# today_date_and_time = datetime.now()
def write_sold(name,phone,date_time,purchased_laptops,cost_of_shipping,final_total):
    with open(str(name) + str(phone) +".txt", "w")as file:
        file.write("\n")
        file.write("\t \t \t \t YADAV Laptop store")
        file.write("\n")
        file.write("\t \t Kamalpokhari, Kathmandu | Phone No: 9824801886 ")
        file.write("\n")
        file.write("****************************************************************************************\n")
        file.write("\n")
        file.write("Laptop Details: ")
        file.write("\n")
        file.write("******************\n")
        file.write("Customer Name:" + str(name))
        file.write("\n")
        file.write("Phone Number: " + str(phone))
        file.write("\n")
        file.write("Date and Time: " + str(date_time))
        file.write("\n")
        file.write("****************************************************************************************\n")
        file.write("\n")
        file.write("Purchase Details are:")
        file.write("\n")
        file.write("***************************************************************************************************\n")
        file.write(" Product Name \t\t Brand \t\t Total Quantity \t\t Unit Price \t Total")
        file.write("\n")
        file.write("***************************************************************************************************\n")
        for i in purchased_laptops:
            file.write(str(i[0]) + "\t" + str(i[1]) + "\t\t" + str(i[2]) + "\t\t\t\t" + str(i[3])+ "\t\t" + "$" + str(i[4])+"\n")
        file.write("***************************************************************************************************\n")
        file.write("\n")
        if cost_of_shipping == 500:
            file.write("Shipping Cost:" +""+ str(cost_of_shipping)+ "\n")
            file.write("\n")
            file.write("Grand Total: $" + str(final_total)+ "\n")
            file.write("\n")
            file.write("Note: Shipping Cost added to grand total" + "\n")
        else:
            file.write("Grand Total: $" + str(final_total))

def write_purchase(name,phone,date_time,purchased_laptops,VAT,final_total, total_with_vat):
    with open(str(name) + str(phone) +".txt", "w")as file:
        file.write("\n")
        file.write("\t \t \t \t YADAV Laptop Shop")
        file.write("\n")
        file.write("\t \t Kamalpokhari, Kathmandu | Phone No: 9824801886 ")
        file.write("\n")
        file.write("################################################################################################\n")
        file.write("Laptop Details: ")
        file.write("\n")
        file.write("####################\n")
        file.write("Customer Name:" + str(name))
        file.write("\n")
        file.write("Phone Number: " + str(phone))
        file.write("\n")
        file.write("Date and Time: " + str(date_time))
        file.write("\n")
        file.write("****************************************************************************************\n")
        file.write("\n")
        file.write("Purchase Details are:")
        file.write("\n")
        file.write("##################################################################################################\n")
        file.write(" Product Name \t\t Brand \t\t Total Quantity \t\t Unit Price \t Total")
        file.write("\n")
        file.write("###################################################################################################\n")
        for i in purchased_laptops:
            file.write(str(i[0]) + "\t" + str(i[1]) + "\t\t" + str(i[2]) + "\t\t\t\t" + str(i[3])+ "\t\t" + "$" + str(i[4])+"\n")
        file.write("######################################################################################################\n")
        file.write("\n")
        file.write("Vat Amount:" +""+ str(VAT)+ "\n")
        file.write("\n")
        file.write("Grand Total: $" + str(total_with_vat)+ "\n")
        file.write("\n")
        file.write("Note: Vat Amount added to grand total" + "\n")
        file.write("\n")
